// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NASRAC.Persistence.Game.DAL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NASRAC.Persistence.Game.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NASRAC.Models.Game.DriverEntities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<double>("DNFOdds")
                        .HasColumnType("double precision");

                    b.Property<double>("IntermediateTrackRating")
                        .HasColumnType("double precision");

                    b.Property<int>("Marketability")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallRating")
                        .HasColumnType("double precision");

                    b.Property<int>("PeakAgeEnd")
                        .HasColumnType("integer");

                    b.Property<int>("PeakAgeStart")
                        .HasColumnType("integer");

                    b.Property<double>("PerformanceRating")
                        .HasColumnType("double precision");

                    b.Property<double>("PotentialRating")
                        .HasColumnType("double precision");

                    b.Property<double>("ProgressionRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RegressionRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RetirementFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("RoadTrackRating")
                        .HasColumnType("double precision");

                    b.Property<double>("ShortTrackRating")
                        .HasColumnType("double precision");

                    b.Property<double>("SuperspeedwayTrackRating")
                        .HasColumnType("double precision");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Driver");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 29,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 64.650999999999996,
                            Marketability = 1,
                            Name = "Judge Quigley",
                            OverallRating = 65.733000000000004,
                            PeakAgeEnd = 40,
                            PeakAgeStart = 30,
                            PerformanceRating = 0.0,
                            PotentialRating = 69.831999999999994,
                            ProgressionRate = 0.045999999999999999,
                            RegressionRate = 0.043999999999999997,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 61.171999999999997,
                            ShortTrackRating = 68.626999999999995,
                            SuperspeedwayTrackRating = 68.480999999999995,
                            TeamId = 30
                        },
                        new
                        {
                            Id = 2,
                            Age = 27,
                            DNFOdds = 0.0,
                            IntermediateTrackRating = 73.230999999999995,
                            Marketability = 9,
                            Name = "Alfonzo Feil",
                            OverallRating = 68.295000000000002,
                            PeakAgeEnd = 36,
                            PeakAgeStart = 34,
                            PerformanceRating = 0.0,
                            PotentialRating = 70.057000000000002,
                            ProgressionRate = 0.084000000000000005,
                            RegressionRate = 0.0060000000000000001,
                            RetirementFactor = 0.001,
                            RoadTrackRating = 72.840999999999994,
                            ShortTrackRating = 57.140000000000001,
                            SuperspeedwayTrackRating = 69.968000000000004,
                            TeamId = 15
                        },
                        new
                        {
                            Id = 3,
                            Age = 31,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 52.159999999999997,
                            Marketability = 9,
                            Name = "Mckenna Lehner",
                            OverallRating = 57.631,
                            PeakAgeEnd = 35,
                            PeakAgeStart = 34,
                            PerformanceRating = 0.0,
                            PotentialRating = 64.994,
                            ProgressionRate = 0.066000000000000003,
                            RegressionRate = 0.028000000000000001,
                            RetirementFactor = 0.002,
                            RoadTrackRating = 66.141000000000005,
                            ShortTrackRating = 62.223999999999997,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 16
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 61.616,
                            Marketability = 5,
                            Name = "Emerson Goldner",
                            OverallRating = 59.731999999999999,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 66.924000000000007,
                            ProgressionRate = 0.057000000000000002,
                            RegressionRate = 0.0030000000000000001,
                            RetirementFactor = 0.002,
                            RoadTrackRating = 58.811999999999998,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 68.501000000000005,
                            TeamId = 29
                        },
                        new
                        {
                            Id = 5,
                            Age = 49,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 87.905000000000001,
                            Marketability = 1,
                            Name = "Claude Koepp",
                            OverallRating = 95.003,
                            PeakAgeEnd = 36,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 100.0,
                            ProgressionRate = 0.070000000000000007,
                            RegressionRate = 0.067000000000000004,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 92.108999999999995,
                            ShortTrackRating = 100.0,
                            SuperspeedwayTrackRating = 100.0,
                            TeamId = 20
                        },
                        new
                        {
                            Id = 6,
                            Age = 30,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 52.914999999999999,
                            Marketability = 10,
                            Name = "Maximus Ferry",
                            OverallRating = 50.728999999999999,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 35,
                            PerformanceRating = 0.0,
                            PotentialRating = 66.388000000000005,
                            ProgressionRate = 0.072999999999999995,
                            RegressionRate = 0.041000000000000002,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 45,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 65.462000000000003,
                            Marketability = 1,
                            Name = "Landen Goyette",
                            OverallRating = 66.881,
                            PeakAgeEnd = 32,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 93.799999999999997,
                            ProgressionRate = 0.083000000000000004,
                            RegressionRate = 0.002,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 72.498000000000005,
                            ShortTrackRating = 65.984999999999999,
                            SuperspeedwayTrackRating = 63.578000000000003,
                            TeamId = 22
                        },
                        new
                        {
                            Id = 8,
                            Age = 35,
                            DNFOdds = 0.0050000000000000001,
                            IntermediateTrackRating = 69.277000000000001,
                            Marketability = 4,
                            Name = "Frederique Schamberger",
                            OverallRating = 78.475999999999999,
                            PeakAgeEnd = 36,
                            PeakAgeStart = 28,
                            PerformanceRating = 0.0,
                            PotentialRating = 85.271000000000001,
                            ProgressionRate = 0.094,
                            RegressionRate = 0.0040000000000000001,
                            RetirementFactor = 0.001,
                            RoadTrackRating = 88.533000000000001,
                            ShortTrackRating = 71.406999999999996,
                            SuperspeedwayTrackRating = 84.685000000000002,
                            TeamId = 28
                        },
                        new
                        {
                            Id = 9,
                            Age = 27,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 65.792000000000002,
                            Marketability = 6,
                            Name = "Eddie Koss",
                            OverallRating = 68.661000000000001,
                            PeakAgeEnd = 34,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 88.748999999999995,
                            ProgressionRate = 0.031,
                            RegressionRate = 0.021000000000000001,
                            RetirementFactor = 0.0050000000000000001,
                            RoadTrackRating = 67.507000000000005,
                            ShortTrackRating = 72.379000000000005,
                            SuperspeedwayTrackRating = 68.965000000000003,
                            TeamId = 28
                        },
                        new
                        {
                            Id = 10,
                            Age = 28,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 75.457999999999998,
                            Marketability = 8,
                            Name = "Lou Schoen",
                            OverallRating = 78.415000000000006,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 28,
                            PerformanceRating = 0.0,
                            PotentialRating = 80.427999999999997,
                            ProgressionRate = 0.075999999999999998,
                            RegressionRate = 0.047,
                            RetirementFactor = 0.0,
                            RoadTrackRating = 79.554000000000002,
                            ShortTrackRating = 89.698999999999998,
                            SuperspeedwayTrackRating = 68.950000000000003,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 11,
                            Age = 27,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 69.513000000000005,
                            Marketability = 10,
                            Name = "Emanuel Lakin",
                            OverallRating = 69.494,
                            PeakAgeEnd = 37,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 79.105000000000004,
                            ProgressionRate = 0.017000000000000001,
                            RegressionRate = 0.016,
                            RetirementFactor = 0.001,
                            RoadTrackRating = 65.269999999999996,
                            ShortTrackRating = 74.677000000000007,
                            SuperspeedwayTrackRating = 68.515000000000001,
                            TeamId = 21
                        },
                        new
                        {
                            Id = 12,
                            Age = 41,
                            DNFOdds = 0.001,
                            IntermediateTrackRating = 50.0,
                            Marketability = 10,
                            Name = "Pedro Harvey",
                            OverallRating = 50.0,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 37,
                            PerformanceRating = 0.0,
                            PotentialRating = 53.161000000000001,
                            ProgressionRate = 0.001,
                            RegressionRate = 0.001,
                            RetirementFactor = 0.002,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 13,
                            Age = 27,
                            DNFOdds = 0.001,
                            IntermediateTrackRating = 50.0,
                            Marketability = 2,
                            Name = "Jefferey Shields",
                            OverallRating = 50.0,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 37,
                            PerformanceRating = 0.0,
                            PotentialRating = 44.603999999999999,
                            ProgressionRate = 0.042999999999999997,
                            RegressionRate = 0.012,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 14,
                            Age = 23,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 73.950000000000003,
                            Marketability = 7,
                            Name = "Delpha Donnelly",
                            OverallRating = 58.421999999999997,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 36,
                            PerformanceRating = 0.0,
                            PotentialRating = 82.516999999999996,
                            ProgressionRate = 0.043999999999999997,
                            RegressionRate = 0.039,
                            RetirementFactor = 0.0,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 59.740000000000002,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 29
                        },
                        new
                        {
                            Id = 15,
                            Age = 25,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 73.533000000000001,
                            Marketability = 8,
                            Name = "Brenda Lind",
                            OverallRating = 72.787999999999997,
                            PeakAgeEnd = 30,
                            PeakAgeStart = 28,
                            PerformanceRating = 0.0,
                            PotentialRating = 88.097999999999999,
                            ProgressionRate = 0.01,
                            RegressionRate = 0.001,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 80.738,
                            ShortTrackRating = 67.578999999999994,
                            SuperspeedwayTrackRating = 69.302000000000007,
                            TeamId = 30
                        },
                        new
                        {
                            Id = 16,
                            Age = 20,
                            DNFOdds = 0.001,
                            IntermediateTrackRating = 61.343000000000004,
                            Marketability = 8,
                            Name = "Judy Ryan",
                            OverallRating = 80.647999999999996,
                            PeakAgeEnd = 28,
                            PeakAgeStart = 27,
                            PerformanceRating = 0.0,
                            PotentialRating = 100.0,
                            ProgressionRate = 0.063,
                            RegressionRate = 0.035000000000000003,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 97.400999999999996,
                            ShortTrackRating = 80.683000000000007,
                            SuperspeedwayTrackRating = 83.165999999999997,
                            TeamId = 26
                        },
                        new
                        {
                            Id = 17,
                            Age = 29,
                            DNFOdds = 0.0030000000000000001,
                            IntermediateTrackRating = 57.866999999999997,
                            Marketability = 5,
                            Name = "Ramona Homenick",
                            OverallRating = 67.329999999999998,
                            PeakAgeEnd = 40,
                            PeakAgeStart = 33,
                            PerformanceRating = 0.0,
                            PotentialRating = 79.165999999999997,
                            ProgressionRate = 0.058000000000000003,
                            RegressionRate = 0.037999999999999999,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 80.881,
                            ShortTrackRating = 69.528999999999996,
                            SuperspeedwayTrackRating = 61.042000000000002,
                            TeamId = 29
                        },
                        new
                        {
                            Id = 18,
                            Age = 33,
                            DNFOdds = 0.0030000000000000001,
                            IntermediateTrackRating = 92.150999999999996,
                            Marketability = 7,
                            Name = "Kathryne Dach",
                            OverallRating = 82.927000000000007,
                            PeakAgeEnd = 30,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 100.0,
                            ProgressionRate = 0.080000000000000002,
                            RegressionRate = 0.069000000000000006,
                            RetirementFactor = 0.001,
                            RoadTrackRating = 81.009,
                            ShortTrackRating = 71.819000000000003,
                            SuperspeedwayTrackRating = 86.730000000000004,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            Age = 29,
                            DNFOdds = 0.0030000000000000001,
                            IntermediateTrackRating = 67.822999999999993,
                            Marketability = 9,
                            Name = "Velva Hackett",
                            OverallRating = 70.978999999999999,
                            PeakAgeEnd = 35,
                            PeakAgeStart = 27,
                            PerformanceRating = 0.0,
                            PotentialRating = 97.941000000000003,
                            ProgressionRate = 0.068000000000000005,
                            RegressionRate = 0.050999999999999997,
                            RetirementFactor = 0.0050000000000000001,
                            RoadTrackRating = 72.573999999999998,
                            ShortTrackRating = 85.415999999999997,
                            SuperspeedwayTrackRating = 58.103999999999999,
                            TeamId = 29
                        },
                        new
                        {
                            Id = 20,
                            Age = 32,
                            DNFOdds = 0.0,
                            IntermediateTrackRating = 56.606999999999999,
                            Marketability = 3,
                            Name = "Harvey O'Hara",
                            OverallRating = 58.231000000000002,
                            PeakAgeEnd = 39,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 73.822999999999993,
                            ProgressionRate = 0.067000000000000004,
                            RegressionRate = 0.019,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 55.543999999999997,
                            ShortTrackRating = 64.409999999999997,
                            SuperspeedwayTrackRating = 56.362000000000002,
                            TeamId = 11
                        },
                        new
                        {
                            Id = 21,
                            Age = 28,
                            DNFOdds = 0.0050000000000000001,
                            IntermediateTrackRating = 50.073999999999998,
                            Marketability = 10,
                            Name = "Adele Smitham",
                            OverallRating = 54.637999999999998,
                            PeakAgeEnd = 37,
                            PeakAgeStart = 32,
                            PerformanceRating = 0.0,
                            PotentialRating = 75.888999999999996,
                            ProgressionRate = 0.076999999999999999,
                            RegressionRate = 0.014999999999999999,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 68.478999999999999,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 23
                        },
                        new
                        {
                            Id = 22,
                            Age = 36,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 50.0,
                            Marketability = 6,
                            Name = "Wilson Dickinson",
                            OverallRating = 50.0,
                            PeakAgeEnd = 34,
                            PeakAgeStart = 33,
                            PerformanceRating = 0.0,
                            PotentialRating = 46.164999999999999,
                            ProgressionRate = 0.051999999999999998,
                            RegressionRate = 0.017000000000000001,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 12
                        },
                        new
                        {
                            Id = 23,
                            Age = 45,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 100.0,
                            Marketability = 6,
                            Name = "Dion Russel",
                            OverallRating = 68.225999999999999,
                            PeakAgeEnd = 39,
                            PeakAgeStart = 28,
                            PerformanceRating = 0.0,
                            PotentialRating = 100.0,
                            ProgressionRate = 0.0060000000000000001,
                            RegressionRate = 0.002,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 72.905000000000001,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 10
                        },
                        new
                        {
                            Id = 24,
                            Age = 32,
                            DNFOdds = 0.001,
                            IntermediateTrackRating = 91.251000000000005,
                            Marketability = 6,
                            Name = "Susan Rempel",
                            OverallRating = 76.122,
                            PeakAgeEnd = 37,
                            PeakAgeStart = 37,
                            PerformanceRating = 0.0,
                            PotentialRating = 89.798000000000002,
                            ProgressionRate = 0.042999999999999997,
                            RegressionRate = 0.0060000000000000001,
                            RetirementFactor = 0.001,
                            RoadTrackRating = 69.966999999999999,
                            ShortTrackRating = 73.206999999999994,
                            SuperspeedwayTrackRating = 70.063999999999993,
                            TeamId = 11
                        },
                        new
                        {
                            Id = 25,
                            Age = 18,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 60.616,
                            Marketability = 5,
                            Name = "Elsie Bogan",
                            OverallRating = 68.597999999999999,
                            PeakAgeEnd = 40,
                            PeakAgeStart = 37,
                            PerformanceRating = 0.0,
                            PotentialRating = 95.858999999999995,
                            ProgressionRate = 0.049000000000000002,
                            RegressionRate = 0.0089999999999999993,
                            RetirementFactor = 0.001,
                            RoadTrackRating = 71.293000000000006,
                            ShortTrackRating = 88.247,
                            SuperspeedwayTrackRating = 54.237000000000002,
                            TeamId = 10
                        },
                        new
                        {
                            Id = 26,
                            Age = 22,
                            DNFOdds = 0.0030000000000000001,
                            IntermediateTrackRating = 72.600999999999999,
                            Marketability = 6,
                            Name = "Marian Kassulke",
                            OverallRating = 61.659999999999997,
                            PeakAgeEnd = 37,
                            PeakAgeStart = 30,
                            PerformanceRating = 0.0,
                            PotentialRating = 95.456999999999994,
                            ProgressionRate = 0.047,
                            RegressionRate = 0.034000000000000002,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 55.927,
                            ShortTrackRating = 56.862000000000002,
                            SuperspeedwayTrackRating = 61.249000000000002,
                            TeamId = 14
                        },
                        new
                        {
                            Id = 27,
                            Age = 35,
                            DNFOdds = 0.0030000000000000001,
                            IntermediateTrackRating = 50.0,
                            Marketability = 5,
                            Name = "Eugenia Blick",
                            OverallRating = 50.067999999999998,
                            PeakAgeEnd = 37,
                            PeakAgeStart = 35,
                            PerformanceRating = 0.0,
                            PotentialRating = 59.268000000000001,
                            ProgressionRate = 0.012,
                            RegressionRate = 0.01,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 50.271000000000001,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 28,
                            Age = 28,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 61.93,
                            Marketability = 2,
                            Name = "Cleo Crona",
                            OverallRating = 78.600999999999999,
                            PeakAgeEnd = 40,
                            PeakAgeStart = 30,
                            PerformanceRating = 0.0,
                            PotentialRating = 95.311000000000007,
                            ProgressionRate = 0.042999999999999997,
                            RegressionRate = 0.016,
                            RetirementFactor = 0.002,
                            RoadTrackRating = 74.789000000000001,
                            ShortTrackRating = 100.0,
                            SuperspeedwayTrackRating = 77.686000000000007,
                            TeamId = 13
                        },
                        new
                        {
                            Id = 29,
                            Age = 14,
                            DNFOdds = 0.001,
                            IntermediateTrackRating = 50.0,
                            Marketability = 2,
                            Name = "Fanny Grant",
                            OverallRating = 50.316000000000003,
                            PeakAgeEnd = 33,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 70.948999999999998,
                            ProgressionRate = 0.067000000000000004,
                            RegressionRate = 0.053999999999999999,
                            RetirementFactor = 0.0,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 51.264000000000003,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 8
                        },
                        new
                        {
                            Id = 30,
                            Age = 29,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 59.606000000000002,
                            Marketability = 6,
                            Name = "Misty Schoen",
                            OverallRating = 69.260000000000005,
                            PeakAgeEnd = 33,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 81.046999999999997,
                            ProgressionRate = 0.065000000000000002,
                            RegressionRate = 0.048000000000000001,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 90.171999999999997,
                            ShortTrackRating = 54.755000000000003,
                            SuperspeedwayTrackRating = 72.507000000000005,
                            TeamId = 16
                        },
                        new
                        {
                            Id = 31,
                            Age = 25,
                            DNFOdds = 0.0,
                            IntermediateTrackRating = 69.852999999999994,
                            Marketability = 5,
                            Name = "Lonnie Nicolas",
                            OverallRating = 59.792000000000002,
                            PeakAgeEnd = 30,
                            PeakAgeStart = 28,
                            PerformanceRating = 0.0,
                            PotentialRating = 90.969999999999999,
                            ProgressionRate = 0.051999999999999998,
                            RegressionRate = 0.041000000000000002,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 69.313999999999993,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 12
                        },
                        new
                        {
                            Id = 32,
                            Age = 23,
                            DNFOdds = 0.0030000000000000001,
                            IntermediateTrackRating = 53.579000000000001,
                            Marketability = 9,
                            Name = "Elenor Schimmel",
                            OverallRating = 50.895000000000003,
                            PeakAgeEnd = 37,
                            PeakAgeStart = 35,
                            PerformanceRating = 0.0,
                            PotentialRating = 71.513000000000005,
                            ProgressionRate = 0.074999999999999997,
                            RegressionRate = 0.029000000000000001,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 24
                        },
                        new
                        {
                            Id = 33,
                            Age = 24,
                            DNFOdds = 0.0050000000000000001,
                            IntermediateTrackRating = 72.013999999999996,
                            Marketability = 3,
                            Name = "Torrance Schaefer",
                            OverallRating = 57.509,
                            PeakAgeEnd = 40,
                            PeakAgeStart = 35,
                            PerformanceRating = 0.0,
                            PotentialRating = 65.281000000000006,
                            ProgressionRate = 0.058999999999999997,
                            RegressionRate = 0.002,
                            RetirementFactor = 0.002,
                            RoadTrackRating = 51.034999999999997,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 56.985999999999997,
                            TeamId = 14
                        },
                        new
                        {
                            Id = 34,
                            Age = 33,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 87.658000000000001,
                            Marketability = 6,
                            Name = "Delilah Zieme",
                            OverallRating = 93.953999999999994,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 30,
                            PerformanceRating = 0.0,
                            PotentialRating = 100.0,
                            ProgressionRate = 0.081000000000000003,
                            RegressionRate = 0.028000000000000001,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 88.158000000000001,
                            ShortTrackRating = 100.0,
                            SuperspeedwayTrackRating = 100.0,
                            TeamId = 15
                        },
                        new
                        {
                            Id = 35,
                            Age = 26,
                            DNFOdds = 0.0,
                            IntermediateTrackRating = 57.387,
                            Marketability = 8,
                            Name = "Brannon Cruickshank",
                            OverallRating = 54.457999999999998,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 31,
                            PerformanceRating = 0.0,
                            PotentialRating = 77.637,
                            ProgressionRate = 0.070999999999999994,
                            RegressionRate = 0.044999999999999998,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 54.344999999999999,
                            ShortTrackRating = 56.098999999999997,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 9
                        },
                        new
                        {
                            Id = 36,
                            Age = 22,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 66.040999999999997,
                            Marketability = 2,
                            Name = "David Gerlach",
                            OverallRating = 70.105000000000004,
                            PeakAgeEnd = 33,
                            PeakAgeStart = 27,
                            PerformanceRating = 0.0,
                            PotentialRating = 91.616,
                            ProgressionRate = 0.024,
                            RegressionRate = 0.021000000000000001,
                            RetirementFactor = 0.0040000000000000001,
                            RoadTrackRating = 84.376999999999995,
                            ShortTrackRating = 71.861999999999995,
                            SuperspeedwayTrackRating = 58.139000000000003,
                            TeamId = 17
                        },
                        new
                        {
                            Id = 37,
                            Age = 43,
                            DNFOdds = 0.002,
                            IntermediateTrackRating = 53.280000000000001,
                            Marketability = 5,
                            Name = "Delbert Nicolas",
                            OverallRating = 51.320999999999998,
                            PeakAgeEnd = 38,
                            PeakAgeStart = 34,
                            PerformanceRating = 0.0,
                            PotentialRating = 51.950000000000003,
                            ProgressionRate = 0.074999999999999997,
                            RegressionRate = 0.031,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 52.003999999999998,
                            TeamId = 29
                        },
                        new
                        {
                            Id = 38,
                            Age = 32,
                            DNFOdds = 0.0,
                            IntermediateTrackRating = 50.0,
                            Marketability = 9,
                            Name = "Devan Beatty",
                            OverallRating = 50.137999999999998,
                            PeakAgeEnd = 40,
                            PeakAgeStart = 29,
                            PerformanceRating = 0.0,
                            PotentialRating = 58.893999999999998,
                            ProgressionRate = 0.0,
                            RegressionRate = 0.0,
                            RetirementFactor = 0.001,
                            RoadTrackRating = 50.551000000000002,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 24
                        },
                        new
                        {
                            Id = 39,
                            Age = 26,
                            DNFOdds = 0.0040000000000000001,
                            IntermediateTrackRating = 50.0,
                            Marketability = 5,
                            Name = "Deven Rohan",
                            OverallRating = 50.0,
                            PeakAgeEnd = 40,
                            PeakAgeStart = 35,
                            PerformanceRating = 0.0,
                            PotentialRating = 36.389000000000003,
                            ProgressionRate = 0.086999999999999994,
                            RegressionRate = 0.027,
                            RetirementFactor = 0.0030000000000000001,
                            RoadTrackRating = 50.0,
                            ShortTrackRating = 50.0,
                            SuperspeedwayTrackRating = 50.0,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 40,
                            Age = 30,
                            DNFOdds = 0.0,
                            IntermediateTrackRating = 82.329999999999998,
                            Marketability = 10,
                            Name = "Merle Nikolaus",
                            OverallRating = 83.884,
                            PeakAgeEnd = 36,
                            PeakAgeStart = 35,
                            PerformanceRating = 0.0,
                            PotentialRating = 100.0,
                            ProgressionRate = 0.096000000000000002,
                            RegressionRate = 0.095000000000000001,
                            RetirementFactor = 0.0,
                            RoadTrackRating = 87.704999999999998,
                            ShortTrackRating = 85.218999999999994,
                            SuperspeedwayTrackRating = 80.281999999999996,
                            TeamId = 26
                        });
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("integer");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double precision");

                    b.Property<int>("LenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalAmountLoaned")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalAmountPaid")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LenderId");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chevy",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chevy",
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ford",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ford",
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toyota",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toyota",
                            VehicleType = 1
                        });
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2022, 2, 6),
                            RaceId = 1,
                            RaceNumber = 1,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2022, 2, 17),
                            RaceId = 2,
                            RaceNumber = 2,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2022, 2, 17),
                            RaceId = 3,
                            RaceNumber = 3,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2022, 2, 20),
                            RaceId = 4,
                            RaceNumber = 4,
                            SeasonId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2022, 2, 27),
                            RaceId = 5,
                            RaceNumber = 5,
                            SeasonId = 1
                        });
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NASRAC Cup Series",
                            Tier = 1,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "NASRAC Bowl Series",
                            Tier = 2,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "NASRAC Truck Series",
                            Tier = 3,
                            VehicleType = 1
                        });
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sponsor");
                });

            modelBuilder.Entity("NASRAC.Models.Game.JoinEntities.TeamManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamManufacturers");
                });

            modelBuilder.Entity("NASRAC.Models.Game.RaceEntities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Laps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stages")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Race");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Laps = 150,
                            Name = "Busch Light Clash at The Coliseum",
                            Stages = 0,
                            TrackId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Laps = 60,
                            Name = "Bluegreen Vacations Duel 1 at DAYTONA",
                            Stages = 2,
                            TrackId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Laps = 60,
                            Name = "Bluegreen Vacations Duel 2 at DAYTONA",
                            Stages = 2,
                            TrackId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Laps = 500,
                            Name = "Daytona 500",
                            Stages = 3,
                            TrackId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            Laps = 200,
                            Name = "Pale Casino 400",
                            Stages = 3,
                            TrackId = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("NASRAC.Models.Game.RaceEntities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Track");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Length = 0.25,
                            Location = "Los Angeles, CA",
                            Name = "Los Angeles Memorial Coliseum",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Length = 2.5,
                            Location = "Daytona Beach, FL",
                            Name = "Daytona International Speedway",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Length = 2.0,
                            Location = "Fontana, CA",
                            Name = "Auto Club Speedway",
                            Type = 2
                        });
                });

            modelBuilder.Entity("NASRAC.Models.Game.Stats.QualifyingStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<double>("FastestTime")
                        .HasColumnType("double precision");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<double>("TopSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.ToTable("QualifyingStats");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Stats.RaceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AveragePosition")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageRunningPosition")
                        .HasColumnType("double precision");

                    b.Property<int>("CautionLapCount")
                        .HasColumnType("integer");

                    b.Property<double>("CautionLapPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("CautionsCaused")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("integer");

                    b.Property<double>("DNFOdds")
                        .HasColumnType("double precision");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<double>("DriverRating")
                        .HasColumnType("double precision");

                    b.Property<double>("FastestTime")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<int>("LapLedCount")
                        .HasColumnType("integer");

                    b.Property<double>("LapLedPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("Top15LapCount")
                        .HasColumnType("integer");

                    b.Property<double>("Top15LapPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("TopSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalLapCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceLog");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Stats.SessionResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AveragePosition")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageRunningPosition")
                        .HasColumnType("double precision");

                    b.Property<int>("CautionLapCount")
                        .HasColumnType("integer");

                    b.Property<double>("CautionLapPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("CautionsCaused")
                        .HasColumnType("integer");

                    b.Property<int>("DNFPosition")
                        .HasColumnType("integer");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<double>("FastestTime")
                        .HasColumnType("double precision");

                    b.Property<int>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<int>("HighestPosition")
                        .HasColumnType("integer");

                    b.Property<int>("LapLedCount")
                        .HasColumnType("integer");

                    b.Property<double>("LapLedPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("LowestPosition")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.Property<int>("StartPosition")
                        .HasColumnType("integer");

                    b.Property<int>("Top15LapCount")
                        .HasColumnType("integer");

                    b.Property<double>("Top15LapPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("TopSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalLapCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.ToTable("SessionResults");
                });

            modelBuilder.Entity("NASRAC.Models.Game.TeamEntities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EquipmentRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallRating")
                        .HasColumnType("double precision");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<double>("PerformanceRating")
                        .HasColumnType("double precision");

                    b.Property<double>("PersonnelRating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentRating = 84.697000000000003,
                            Name = "Purple Finish Line Motorsports",
                            OverallRating = 86.238,
                            PerformanceRating = 0.0,
                            PersonnelRating = 87.780000000000001
                        },
                        new
                        {
                            Id = 2,
                            EquipmentRating = 85.504000000000005,
                            Name = "Cosmos Racing Group LLC",
                            OverallRating = 84.715000000000003,
                            PerformanceRating = 0.0,
                            PersonnelRating = 83.926000000000002
                        },
                        new
                        {
                            Id = 3,
                            EquipmentRating = 90.649000000000001,
                            Name = "Black Mountain Racing Limited",
                            OverallRating = 95.323999999999998,
                            PerformanceRating = 0.0,
                            PersonnelRating = 100.0
                        },
                        new
                        {
                            Id = 4,
                            EquipmentRating = 93.561999999999998,
                            Name = "Nitro Racing Team Incorporated",
                            OverallRating = 88.227000000000004,
                            PerformanceRating = 0.0,
                            PersonnelRating = 82.891999999999996
                        },
                        new
                        {
                            Id = 5,
                            EquipmentRating = 90.043999999999997,
                            Name = "Burnout Racing Team Ltd.",
                            OverallRating = 94.989000000000004,
                            PerformanceRating = 0.0,
                            PersonnelRating = 99.933999999999997
                        },
                        new
                        {
                            Id = 6,
                            EquipmentRating = 100.0,
                            Name = "Valley Racing Group Inc.",
                            OverallRating = 100.0,
                            PerformanceRating = 0.0,
                            PersonnelRating = 100.0
                        },
                        new
                        {
                            Id = 7,
                            EquipmentRating = 80.948999999999998,
                            Name = "Safari Racing Limited",
                            OverallRating = 79.384,
                            PerformanceRating = 0.0,
                            PersonnelRating = 77.817999999999998
                        },
                        new
                        {
                            Id = 8,
                            EquipmentRating = 100.0,
                            Name = "White Sun Racing Group LLC",
                            OverallRating = 92.085999999999999,
                            PerformanceRating = 0.0,
                            PersonnelRating = 84.173000000000002
                        },
                        new
                        {
                            Id = 9,
                            EquipmentRating = 84.114000000000004,
                            Name = "Comet Racing Group Limited",
                            OverallRating = 84.840999999999994,
                            PerformanceRating = 0.0,
                            PersonnelRating = 85.567999999999998
                        },
                        new
                        {
                            Id = 10,
                            EquipmentRating = 80.605999999999995,
                            Name = "Crest Racing Group Incorporated",
                            OverallRating = 84.256,
                            PerformanceRating = 0.0,
                            PersonnelRating = 87.905000000000001
                        },
                        new
                        {
                            Id = 11,
                            EquipmentRating = 67.019000000000005,
                            Name = "Valley Racing Group Ltd.",
                            OverallRating = 79.896000000000001,
                            PerformanceRating = 0.0,
                            PersonnelRating = 92.772000000000006
                        },
                        new
                        {
                            Id = 12,
                            EquipmentRating = 93.924000000000007,
                            Name = "Asteroid Racing Group Limited",
                            OverallRating = 91.468999999999994,
                            PerformanceRating = 0.0,
                            PersonnelRating = 89.013999999999996
                        },
                        new
                        {
                            Id = 13,
                            EquipmentRating = 85.638999999999996,
                            Name = "Cosmos Racing Group Incorporated",
                            OverallRating = 88.989000000000004,
                            PerformanceRating = 0.0,
                            PersonnelRating = 92.338999999999999
                        },
                        new
                        {
                            Id = 14,
                            EquipmentRating = 76.866,
                            Name = "Yellow Canyon Racing Ltd.",
                            OverallRating = 83.939999999999998,
                            PerformanceRating = 0.0,
                            PersonnelRating = 91.013999999999996
                        },
                        new
                        {
                            Id = 15,
                            EquipmentRating = 55.991999999999997,
                            Name = "Galaxy Racing Group Inc.",
                            OverallRating = 52.996000000000002,
                            PerformanceRating = 0.0,
                            PersonnelRating = 50.0
                        },
                        new
                        {
                            Id = 16,
                            EquipmentRating = 82.164000000000001,
                            Name = "Red Peak Racing Group Limited",
                            OverallRating = 91.081999999999994,
                            PerformanceRating = 0.0,
                            PersonnelRating = 100.0
                        },
                        new
                        {
                            Id = 17,
                            EquipmentRating = 90.244,
                            Name = "Yellow Sun Racing Incorporated",
                            OverallRating = 89.813999999999993,
                            PerformanceRating = 0.0,
                            PersonnelRating = 89.382999999999996
                        },
                        new
                        {
                            Id = 18,
                            EquipmentRating = 81.619,
                            Name = "Vertex Racing Team LLC",
                            OverallRating = 79.281000000000006,
                            PerformanceRating = 0.0,
                            PersonnelRating = 76.942999999999998
                        },
                        new
                        {
                            Id = 19,
                            EquipmentRating = 57.731999999999999,
                            Name = "Crown Racing Group Limited",
                            OverallRating = 66.007000000000005,
                            PerformanceRating = 0.0,
                            PersonnelRating = 74.281999999999996
                        },
                        new
                        {
                            Id = 20,
                            EquipmentRating = 84.073999999999998,
                            Name = "Mountain Racing Team Incorporated",
                            OverallRating = 91.573999999999998,
                            PerformanceRating = 0.0,
                            PersonnelRating = 99.075000000000003
                        },
                        new
                        {
                            Id = 21,
                            EquipmentRating = 89.856999999999999,
                            Name = "Finish Line Racing Team Limited",
                            OverallRating = 94.927999999999997,
                            PerformanceRating = 0.0,
                            PersonnelRating = 100.0
                        },
                        new
                        {
                            Id = 22,
                            EquipmentRating = 79.843999999999994,
                            Name = "Green Ridge Racing Group Limited",
                            OverallRating = 76.597999999999999,
                            PerformanceRating = 0.0,
                            PersonnelRating = 73.352000000000004
                        },
                        new
                        {
                            Id = 23,
                            EquipmentRating = 95.097999999999999,
                            Name = "Crest Racing Ltd.",
                            OverallRating = 89.847999999999999,
                            PerformanceRating = 0.0,
                            PersonnelRating = 84.599000000000004
                        },
                        new
                        {
                            Id = 24,
                            EquipmentRating = 59.725999999999999,
                            Name = "Moon Racing Team LLC",
                            OverallRating = 59.476999999999997,
                            PerformanceRating = 0.0,
                            PersonnelRating = 59.228000000000002
                        },
                        new
                        {
                            Id = 25,
                            EquipmentRating = 66.671000000000006,
                            Name = "Vertex Racing Incorporated",
                            OverallRating = 67.686000000000007,
                            PerformanceRating = 0.0,
                            PersonnelRating = 68.700999999999993
                        },
                        new
                        {
                            Id = 26,
                            EquipmentRating = 94.129999999999995,
                            Name = "Galaxy Racing Group",
                            OverallRating = 94.781999999999996,
                            PerformanceRating = 0.0,
                            PersonnelRating = 95.433000000000007
                        },
                        new
                        {
                            Id = 27,
                            EquipmentRating = 83.311999999999998,
                            Name = "Adrenaline Motorsports",
                            OverallRating = 91.656000000000006,
                            PerformanceRating = 0.0,
                            PersonnelRating = 100.0
                        },
                        new
                        {
                            Id = 28,
                            EquipmentRating = 100.0,
                            Name = "Green Meteor Racing",
                            OverallRating = 93.262,
                            PerformanceRating = 0.0,
                            PersonnelRating = 86.522999999999996
                        },
                        new
                        {
                            Id = 29,
                            EquipmentRating = 50.0,
                            Name = "White Spire Racing Team Ltd.",
                            OverallRating = 74.902000000000001,
                            PerformanceRating = 0.0,
                            PersonnelRating = 99.802999999999997
                        },
                        new
                        {
                            Id = 30,
                            EquipmentRating = 74.614000000000004,
                            Name = "Apex Racing Group LLC",
                            OverallRating = 74.548000000000002,
                            PerformanceRating = 0.0,
                            PersonnelRating = 74.483000000000004
                        });
                });

            modelBuilder.Entity("NASRAC.Models.Game.TeamEntities.TeamFinancials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamFinancials");
                });

            modelBuilder.Entity("NASRAC.Models.WebApp.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NASRAC.Models.WebApp.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NASRAC.Models.WebApp.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NASRAC.Models.WebApp.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NASRAC.Models.WebApp.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NASRAC.Models.Game.DriverEntities.Driver", b =>
                {
                    b.HasOne("NASRAC.Models.Game.TeamEntities.Team", "Team")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Car", b =>
                {
                    b.HasOne("NASRAC.Models.Game.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NASRAC.Models.Game.TeamEntities.Team", "Team")
                        .WithMany("Cars")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Loan", b =>
                {
                    b.HasOne("NASRAC.Models.Game.TeamEntities.Team", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NASRAC.Models.Game.TeamEntities.Team", "Lender")
                        .WithMany()
                        .HasForeignKey("LenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("Lender");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Schedule", b =>
                {
                    b.HasOne("NASRAC.Models.Game.RaceEntities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("NASRAC.Models.Game.JoinEntities.TeamManufacturers", b =>
                {
                    b.HasOne("NASRAC.Models.Game.Entities.Manufacturer", "Manufacturer")
                        .WithMany("TeamManufacturers")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NASRAC.Models.Game.TeamEntities.Team", "Team")
                        .WithMany("TeamManufacturers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NASRAC.Models.Game.RaceEntities.Race", b =>
                {
                    b.HasOne("NASRAC.Models.Game.RaceEntities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Stats.QualifyingStats", b =>
                {
                    b.HasOne("NASRAC.Models.Game.DriverEntities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NASRAC.Models.Game.RaceEntities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Stats.RaceLog", b =>
                {
                    b.HasOne("NASRAC.Models.Game.DriverEntities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NASRAC.Models.Game.RaceEntities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Stats.SessionResults", b =>
                {
                    b.HasOne("NASRAC.Models.Game.DriverEntities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NASRAC.Models.Game.RaceEntities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("NASRAC.Models.Game.TeamEntities.Team", b =>
                {
                    b.HasOne("NASRAC.Models.WebApp.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NASRAC.Models.Game.TeamEntities.TeamFinancials", b =>
                {
                    b.HasOne("NASRAC.Models.Game.TeamEntities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NASRAC.Models.Game.Entities.Manufacturer", b =>
                {
                    b.Navigation("TeamManufacturers");
                });

            modelBuilder.Entity("NASRAC.Models.Game.TeamEntities.Team", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Drivers");

                    b.Navigation("TeamManufacturers");
                });
#pragma warning restore 612, 618
        }
    }
}
